test:
	__test/C_glabrata_test_runner.pl

clean:
	rm -rf ./trinity_out_dir ./GSNO-A ./GSNO-B ./GSNO-C ./STND-A ./STND-B ./STND-C ./__TrinDemo_checkpoints_dir
	rm -f ./bowtie* ./ExN50* ./salmon* ./blastx* ./mini_sprot.pep.* ./quant_files.txt ./index_* ./__tmp_runTMM.R
