test:
	__test/mini_humanX_test_runner.pl

clean:
	rm -rf ./trinity_out_dir ./minigenome.fa.gmap
	rm -f ./minigenome.fa.* ./pipeliner.* ./minigenome.gtf.* ./stringtie.gtf ./alignments.* ./hisat.* ./*.ok

